//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblDay()
        {
            this.TblHosSpecDayRel = new HashSet<TblHosSpecDayRel>();
        }
    
        public int DayId { get; set; }
        public Nullable<short> DayOfWeek { get; set; }
        public bool IsWorking { get; set; }
        public Nullable<System.TimeSpan> StartShift { get; set; }
        public Nullable<System.TimeSpan> EndShift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHosSpecDayRel> TblHosSpecDayRel { get; set; }
    }
}
