//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHosSpecDayRel
    {
        public int HosSpecDayRelId { get; set; }
        public int HosSpecId { get; set; }
        public int DayId { get; set; }
    
        public virtual TblDay TblDay { get; set; }
        public virtual TblHospitalSpecialityRel TblHospitalSpecialityRel { get; set; }
    }
}
