//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHospital()
        {
            this.TblHospitalSpecialityRel = new HashSet<TblHospitalSpecialityRel>();
            this.TblImage = new HashSet<TblImage>();
            this.TblTicket = new HashSet<TblTicket>();
        }
    
        public int HospitalId { get; set; }
        public string Name { get; set; }
        public int LocationId { get; set; }
        public string Address { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string TellNo { get; set; }
        public string TellNo2 { get; set; }
        public int AdminId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ImageUrl { get; set; }
        public int CatagoryId { get; set; }
        public string AboutUs { get; set; }
        public short Fee { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TblCatagory TblCatagory { get; set; }
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHospitalSpecialityRel> TblHospitalSpecialityRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblImage> TblImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicket> TblTicket { get; set; }
        public virtual TblLocation TblLocation { get; set; }
    }
}
