//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHospitalSpecialityRel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHospitalSpecialityRel()
        {
            this.TblHosSpecDayRel = new HashSet<TblHosSpecDayRel>();
            this.TblOrder = new HashSet<TblOrder>();
        }
    
        public int HospitalSpecialityRelId { get; set; }
        public int HospitalId { get; set; }
        public Nullable<int> SpecialityId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TblHospital TblHospital { get; set; }
        public virtual TblSpeciality TblSpeciality { get; set; }
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHosSpecDayRel> TblHosSpecDayRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrder> TblOrder { get; set; }
    }
}
