//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrder
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int HospitalSpecialityRelId { get; set; }
        public System.DateTime Time { get; set; }
        public long Price { get; set; }
        public bool IsPayed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long DoctorsPart { get; set; }
        public long HospitalsPart { get; set; }
        public int SettlementStatus { get; set; }
    
        public virtual TblHospitalSpecialityRel TblHospitalSpecialityRel { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
