//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTicket()
        {
            this.TblTicket1 = new HashSet<TblTicket>();
        }
    
        public int TicketId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int FromId { get; set; }
        public int HospitalId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual TblHospital TblHospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicket> TblTicket1 { get; set; }
        public virtual TblTicket TblTicket2 { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
