//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUser()
        {
            this.TblHospital = new HashSet<TblHospital>();
            this.TblHospitalSpecialityRel = new HashSet<TblHospitalSpecialityRel>();
            this.TblOrder = new HashSet<TblOrder>();
            this.TblTicket = new HashSet<TblTicket>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string TellNo { get; set; }
        public string IdentificationNo { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public string ImageUrl { get; set; }
        public bool Gender { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<short> VisitTime { get; set; }
        public long VisitPrice { get; set; }
        public string Address { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string DoctorDescription { get; set; }
        public bool IsActive { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsDeleted { get; set; }
        public string Auth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHospital> TblHospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHospitalSpecialityRel> TblHospitalSpecialityRel { get; set; }
        public virtual TblLocation TblLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrder> TblOrder { get; set; }
        public virtual TblRole TblRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicket> TblTicket { get; set; }
    }
}
